# Generated by Django 4.0 on 2021-12-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0002_jop_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='description',
            field=models.TextField(default=' ', max_length=5000),
            preserve_default=False,
        ),
    ]
